#ifndef ENV_H

#define ENV_H
#define DEBUGGING 0
#define TESTING 0
#define PRODUCTION 1

#define BINARY_THRESHOLD 0
#define OTSU 1

#define BINARY_THRESHOLD_VALUE 90
#define HISTOGRAM_SIZE 256

#define THRESHOLDING_METHOD BINARY_THRESHOLD

#endif